version: '3.7'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --email admin@example.com --username admin && python manage.py runserver 0.0.0.0:1337"
    env_file:
      - ./backend/.env
    ports:
      - 1337:1337
    depends_on:
      - db
  
  db:
    image: postgres:12.6
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    

volumes:
  postgres_data:
